server:
  port: 8081
# tomcat:
  #    remoteip:
  #      remote-ip-header: x-forwarded-for
  #      protocol-header: x-forwarded-proto

# 配置参考：https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
spring:
  datasource:
    url: jdbc:mysql://10.2.2.199:3306/wechat?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 500
    minIdle: 30
    validationQueryTimeout: 5000
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
  mvc:
    view:
      prefix: /
      suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:spring-logback.xml


# token配置
jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 5
  header: token
# 系统基础配置
system:
    captcha-enable: true
    captcha-loginFailNumEnable: 1
    ignored-token-path: /login,/kaptcha,/manage/**
# 微信认证
wechat:
  token: xw
  appID: wxbdfcead38fdfeb8d
  appsecret: cde9e1f344cf6bf9f958003573ce348c
  urlMaps: {
      accessToken: "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s", #获取token
      userList: "https://api.weixin.qq.com/cgi-bin/user/get?access_token=%s&next_openid=%s",
      templateList: "https://api.weixin.qq.com/cgi-bin/template/get_all_private_template?access_token=%s",
      sendTemplateMessage: "https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=%s", #发送模板消息
      code: "https://open.weixin.qq.com/connect/oauth2/authorize?appid=%s&redirect_uri=%s&response_type=code&scope=snsapi_userinfo&state=STATE#wechat_redirect",
      codeExchangeAccessToken: "https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code"
  }
  manageTemplateId: 56qqkcgnpjuXI8pMmVZdB7mDFW6fOTEyzjwQ7O-qfIw #客户经理模板Id
  customerTemplateId: gPS2OaJCtsyYxX5VY88gRTiplQP7d0NFzjtYSeuDrEo #客户模板Id
  redirectUriCodeUrl: "http://e8aa6f145531.ngrok.io/wechat/codeExchangeAccessToken" # 获取code后的回调url,需要在 网页帐号->网页授权获取用户基本信息下配置 授权回调页面域名

# ossim对接
ossim:
  protocol: https
  ip: 10.2.10.130
  port: 8011
