server:
  port: 8081

# 配置参考：https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
spring:
  datasource:
    url: jdbc:mysql://10.2.2.199:3306/wechat?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 500
    minIdle: 30
    validationQueryTimeout: 5000
    testWhileIdle: true
    validationQuery: SELECT 1 FROM DUAL
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
logging:
  config: classpath:spring-logback.xml
# token配置
jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 5
  header: token
# 系统基础配置
system:
  base:
    captcha-enable: true
    captcha-loginFailNumEnable: 1
# 不需要认证的url
path:
  ignored-token-path: /login,/kaptcha

